[package]
name = "tf-ncl"
version = "0.1.0"
authors = ["vkleen"]
edition = "2018"

[dependencies]
clap = { version = "4.0.4", features = ["cargo", "derive"] }
anyhow = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
nickel-lang = "0.2"
pretty = "0.11"
